ALEXANDRIA_IGDB_CLIENT_ID: ENC[AES256_GCM,data:644A6xxvEerziQ13meVHs/HWDnG2/QsZvlnWHE65,iv:RFsMh541MFiVpBe07ASYyNZhwZcbELGR2TCoEUycaBU=,tag:3LDTDZ/DWhMSQYliiNuulQ==,type:str]
ALEXANDRIA_IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:p8XzRzWCOXQxRWJVmo5ARqfmW+HXIjVVKtRXJaIx,iv:oK1sLBkieF5Z/qDSWp12oITXgcdECxPp0c61ztkN87c=,tag:YokmreRmVl2JJiqa70JpzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNR1JqTDM4RkdjSVZWNTRC
            RjZVQTFkazdvQmJzeXJPRndsaVplcjZRVWw4ClBxYlAvWTBxRUNvZDdCTXBIMFVs
            QTZldjVNTS9TZjZEV2VRSUZJYWxOeEEKLS0tIFpiNW5WMXVpeDNUMXBVTkVaSmRw
            Szg0bjZRRWI4U0tDQ0o5ZmtKNzhCMHcKTU72O2L4N5te2QVpQiWOR2DKaYANnE4D
            HiI+uI71HDSxlzFshfFlQCf+iok5OG5Q5PAA6xJdBJ4zGJ3Nc/KXWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age139a7x0htpfs83f52k9kd4qvpyjup89ypdjev7f4r8767d6ljw4wq04vt3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeWNOOGxjV2VBdHNmb1h6
            RWtEeHo5amp3amhocERMaUpUWmt5dVVWU2hrClBGYXhHbnFoTGpneXhhdzhOeWw2
            OGZBSlZJQW4ydVduYUZuY1JGcHpldkkKLS0tIHJjTjdLdFRsNDEvZUpiU0VJL3Bl
            NjhjeWVIVkVKSGl2MHlVYk9SRVM5YXcKlD/Q+zv1dMxCiP1H7+BSX6NDWT5Q0VlP
            +akfjE3qC2EGOkVzgcdyZlG6GAXabyrIoY2K7AW7qTncX5YEatmXsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T07:04:10Z"
    mac: ENC[AES256_GCM,data:wl+tJyMVNTIv5fuU8ZBXtSw5mn0FPBCMPWJvwPHbtfnSE/Uqlv8tcQdhuJ3jJPn9OADDXQnaODJnL718liit610wzht2yfRww5n7jn3WekMVTSbcliSB/tcAOAB37I+3SzYxgFkKhjzOST5e7hjxguk7KKFWRmleBfCetM0N6yY=,iv:0fcLivA02+Rw8voFtbJRFcRvWAbWywJ44Q2MbbM477g=,tag:J6/K0Lw83MOxnZQL1dJdhA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
