keys:
  - &tristan age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
  - &tahoe age139a7x0htpfs83f52k9kd4qvpyjup89ypdjev7f4r8767d6ljw4wq04vt3h
creation_rules:
  - path_regex: devops/secrets.yaml
    key_groups:
      - age:
          - *tristan
          - *tahoe
