version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres
    env_file: .env
    healthcheck:
      test: [ CMD, pg_isready, -U, $POSTGRES_USER, -d, $POSTGRES_DB ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./run/db/data:/var/lib/postgresql/data
      - ./run/db/logs:/var/lib/postgresql/pg_log
    ports:
      - 5432:5432
  migrate:
    build:
      context: src-tauri
      dockerfile: migrate.Dockerfile
    container_name: migrate
    env_file: .env
    environment:
      DATABASE_URL: postgresql://$POSTGRES_USER:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/$POSTGRES_DB
    command: [ cargo, sqlx, migrate, run ]
    depends_on:
      db:
        condition: service_healthy
  dummy_data:
    image: postgres:15
    container_name: dummy_data
    working_dir: /data
    env_file: .env
    environment:
      PGPASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./src-tauri/tests/data:/data
    command: [ psql, -h, $POSTGRES_HOST, -U, $POSTGRES_USER, -d, $POSTGRES_DB, -f, dummy.sql]
    depends_on:
      - migrate
