[package]
name = "backend"

authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
actix-web = "4.3.1"
chrono = "0.4.39"
futures = "0.3.30"
quick-xml = { version = "0.31.0", features = ["serialize"] }
regex = "1.10.6"
sqlx = { version = "0.7.3", features = [
  "runtime-async-std",
  "tls-native-tls",
  "postgres",
  "time",
  "migrate",
] }

models.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
