[package]
name = "alexandria-tauri"
version = "0.0.1"
authors = ["Tristan Schrader", "Tahoe Schrader"]
description = "Track your media"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-rc.0", features = [] }

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
tauri = { version = "2.0.0-rc.0", features = [] }
tauri-plugin-shell = "2.0.0-rc.0"

[lib]
name = "alexandria_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
