[package]
name = "desktop"

authors.workspace = true
edition.workspace = true
version.workspace = true

[build-dependencies]
tauri-build = { version = "2.0.0-rc.0", features = [] }

[dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
tauri = { version = "2.0.0-rc.0", features = [] }
tauri-plugin-shell = "2.0.0-rc.0"

[lib]
name = "alexandria_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
