[package]
name = "cli"

authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["all-widgets", "serde"] }
tui-textarea = "0.7.0"

models.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
